version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
  firefox:
    image: selenium/node-firefox
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
  Get_actual_title:
    image: arif434/selenium_dockerfile_test:latest
    container_name: Get_actual_title
    depends_on:
      - firefox
      - chrome
    environment:
      - MODULE=Get_actual_title.xml
      - BROWSER=firefox
      - SELENIUM_HUB=selenium-hub
    volumes:
      - /home/Get_actual_title-result:/test-output
  Get_actual_url:
    image: arif434/selenium_dockerfile_test:latest
    container_name: Get_actual_url
    depends_on:
      - firefox
      - chrome
    environment:
      - MODULE=Get_actual_url.xml
      - BROWSER=chrome
      - SELENIUM_HUB=selenium-hub
    volumes:
      - /home/Get_actual_title-result:/test-output    